[package]
name = "jacobi"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.4"
num-bigint-dig = "0.8.4"
num-integer = "0.1.44"
num-traits = "0.2.18"

[dev-dependencies]
rand = "0.8.4"

[lib]
name = "jacobi"
crate-type = ["cdylib"]